"""Added exercises and bodyparts relation

Revision ID: d3f21d5e744a
Revises: 
Create Date: 2017-09-05 08:58:00.376750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f21d5e744a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bodypart_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('bodypart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bodypart_id'], ['bodyparts.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bodypart_exercises')
    op.drop_table('exercises')
    op.drop_table('bodyparts')
    # ### end Alembic commands ###
