"""empty message

Revision ID: dd2bc21baaf8
Revises: 
Create Date: 2017-09-02 23:32:38.007020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2bc21baaf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bodypart_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('bodypart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bodypart_id'], ['bodyparts.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bodypart_exercises')
    op.drop_table('exercises')
    op.drop_table('bodyparts')
    # ### end Alembic commands ###
